version: "3"

services:
  fastapi_server:
    container_name: fastapi_server
    image: python:3-alpine
    restart: always
    depends_on:
      - nginx
    networks:
      - stathub-network
    healthcheck:
      test: [ "CMD", "curl", "localhost/healthcheck" ]
    volumes:
      - "./:/app"
      - "log-volume:/logs"
      - "/var/run/docker.sock:/var/run/docker.sock"
    working_dir: /app
    command:
    - |
       apt clean && apt update && apt install curl -y
       pip install --no-cache-dir --upgrade -r requirements.txt
       uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 80
    ports:
      - "8082:80"

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    networks:
      - stathub-network
    healthcheck:
      test: [ "CMD", "curl", "localhost/health" ]
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - log-volume:/var/log/nginx
    ports:
      - "8000:80"
    environment:
      - NGINX_PORT=80

volumes:
  log-volume:
networks:
  app-network:
    driver: bridge